import json
import os
import sys
import tempfile
import unittest
from unittest.mock import patch

AI_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if AI_DIR not in sys.path:
    sys.path.insert(0, AI_DIR)
# enhance.py 在导入时读取 template.txt / system.txt，因此测试的工作目录必须是 ai/
os.chdir(AI_DIR)

import enhance  # noqa: E402
from summary_cache import build_ai_meta  # noqa: E402

AI_META = build_ai_meta("deepseek-flash", "Chinese", enhance.system, enhance.template)
AI_FIELDS = {
    "tldr": "一句话摘要",
    "motivation": "动机",
    "method": "方法",
    "result": "结果",
    "conclusion": "结论",
}


def make_items(count: int = 3) -> list:
    return [
        {"id": f"2609.0000{i}", "summary": f"Abstract number {i}."}
        for i in range(count)
    ]


class ReuseTests(unittest.TestCase):
    def test_cached_summaries_are_reused_without_calling_the_llm(self):
        items = make_items()
        cache = {
            item["id"]: {**item, "AI": dict(AI_FIELDS), "ai_meta": AI_META}
            for item in items
        }

        with patch.object(enhance, "is_sensitive", return_value=False), patch.object(
            enhance, "build_chain", side_effect=AssertionError("LLM must not be called")
        ):
            result = enhance.process_all_items(
                items, "deepseek-flash", "Chinese", 1, cache=cache, ai_meta=AI_META
            )

        self.assertEqual(3, len([item for item in result if item]))
        self.assertEqual("一句话摘要", result[0]["AI"]["tldr"])
        self.assertEqual(AI_META, result[0]["ai_meta"])

    def test_entries_without_meta_are_recomputed(self):
        """Catches reuse of summaries generated by an older model or prompt."""
        items = make_items(1)
        cache = {items[0]["id"]: {**items[0], "AI": dict(AI_FIELDS)}}
        called = []

        def fake_chain(model_name):
            called.append(model_name)
            raise RuntimeError("stop here")

        with patch.object(enhance, "is_sensitive", return_value=False), patch.object(
            enhance, "build_chain", side_effect=fake_chain
        ):
            with self.assertRaises(RuntimeError):
                enhance.process_all_items(
                    items, "deepseek-flash", "Chinese", 1, cache=cache, ai_meta=AI_META
                )

        self.assertEqual(["deepseek-flash"], called)


class PartialWriteTests(unittest.TestCase):
    def test_finished_items_are_on_disk_after_a_failed_run(self):
        """Catches losing every processed paper when the run dies halfway."""
        with tempfile.TemporaryDirectory() as tmp:
            data_path = os.path.join(tmp, "2026-09-19.jsonl")
            items = make_items(3)
            with open(data_path, "w", encoding="utf-8") as handle:
                for item in items:
                    handle.write(json.dumps(item) + "\n")

            def fake_process(data, model_name, language, max_workers, cache=None, ai_meta=None, on_item=None):
                on_item({**data[0], "AI": dict(AI_FIELDS), "ai_meta": ai_meta})
                raise RuntimeError("network died")

            with patch.object(sys, "argv", ["enhance.py", "--data", data_path]), patch.object(
                enhance, "process_all_items", side_effect=fake_process
            ), patch.dict(os.environ, {"MODEL_NAME": "deepseek-flash", "LANGUAGE": "Chinese"}):
                with self.assertRaises(RuntimeError):
                    enhance.main()

            target = os.path.join(tmp, "2026-09-19_AI_enhanced_Chinese.jsonl")
            with open(target, encoding="utf-8") as handle:
                written = [json.loads(line) for line in handle if line.strip()]

        self.assertEqual(1, len(written))
        self.assertEqual("2609.00000", written[0]["id"])
        self.assertEqual(AI_META, written[0]["ai_meta"])

    def test_successful_run_is_rewritten_in_input_order(self):
        with tempfile.TemporaryDirectory() as tmp:
            data_path = os.path.join(tmp, "2026-09-19.jsonl")
            items = make_items(3)
            with open(data_path, "w", encoding="utf-8") as handle:
                for item in items:
                    handle.write(json.dumps(item) + "\n")

            def fake_process(data, model_name, language, max_workers, cache=None, ai_meta=None, on_item=None):
                results = []
                for item in reversed(data):  # 故意乱序完成
                    result = {**item, "AI": dict(AI_FIELDS), "ai_meta": ai_meta}
                    on_item(result)
                    results.append(result)
                return list(reversed(results))

            with patch.object(sys, "argv", ["enhance.py", "--data", data_path]), patch.object(
                enhance, "process_all_items", side_effect=fake_process
            ), patch.dict(os.environ, {"MODEL_NAME": "deepseek-flash", "LANGUAGE": "Chinese"}):
                enhance.main()

            target = os.path.join(tmp, "2026-09-19_AI_enhanced_Chinese.jsonl")
            with open(target, encoding="utf-8") as handle:
                written = [json.loads(line) for line in handle if line.strip()]

        self.assertEqual([item["id"] for item in items], [item["id"] for item in written])


if __name__ == "__main__":
    unittest.main()
